/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package questionario;

import java.awt.Color;

/**
 *
 * @author ve495
 */
public class Questoes extends javax.swing.JFrame {

    /**
     * Creates new form Questoes
     */
    public Questoes() {
        initComponents();
        grupoQuestao1.add(opcao1Questao1);
        grupoQuestao1.add(opcao2Questao1);
        grupoQuestao1.add(opcao3Questao1);
        
        grupoQuestao3.add(opcao1Questao3);
        grupoQuestao3.add(opcao2Questao3);
        grupoQuestao3.add(opcao3Questao3);
        
        grupoQuestao6.add(opcao1Questao6);
        grupoQuestao6.add(opcao2Questao6);
        grupoQuestao6.add(opcao3Questao6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoQuestao1 = new javax.swing.ButtonGroup();
        grupoQuestao3 = new javax.swing.ButtonGroup();
        grupoQuestao6 = new javax.swing.ButtonGroup();
        grupoQuestao8 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblQuestao1 = new javax.swing.JLabel();
        opcao1Questao1 = new javax.swing.JRadioButton();
        opcao2Questao1 = new javax.swing.JRadioButton();
        opcao3Questao1 = new javax.swing.JRadioButton();
        lblResultado1 = new javax.swing.JLabel();
        lblQuestao2 = new javax.swing.JLabel();
        lblResultado2 = new javax.swing.JLabel();
        lblResultado3 = new javax.swing.JLabel();
        opcao1Questao3 = new javax.swing.JRadioButton();
        opcao2Questao3 = new javax.swing.JRadioButton();
        opcao3Questao3 = new javax.swing.JRadioButton();
        lblQuestao3 = new javax.swing.JLabel();
        lblQuestao4 = new javax.swing.JLabel();
        lblResultado4 = new javax.swing.JLabel();
        lblResultado5 = new javax.swing.JLabel();
        lblQuestao5 = new javax.swing.JLabel();
        opcao2Questao6 = new javax.swing.JRadioButton();
        opcao3Questao6 = new javax.swing.JRadioButton();
        lblQuestao6 = new javax.swing.JLabel();
        lblResultado6 = new javax.swing.JLabel();
        opcao1Questao6 = new javax.swing.JRadioButton();
        lblResultado7 = new javax.swing.JLabel();
        lblQuestao7 = new javax.swing.JLabel();
        lblResultado8 = new javax.swing.JLabel();
        lblQuestao8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbQuestao2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfQuestao4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfQuestao5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfQuestao7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfQuestao8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Questionário de Matemática");

        lblQuestao1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuestao1.setText("01. Qual o fatorial de um número n, qualquer?");

        opcao1Questao1.setText("n * (n -1) * (n-2)...1");
        opcao1Questao1.setActionCommand("n * (n -1) * (n-2)....1");

        opcao2Questao1.setText("n * (n -2) * (n-4)...1");

        opcao3Questao1.setText("n * (n -2) * (n-4)...10");

        lblResultado1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lblQuestao2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuestao2.setText("02. Como é representado o fatorial?");

        lblResultado2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lblResultado3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        opcao1Questao3.setText("n * (n-1)!!");

        opcao2Questao3.setText("n * (n-1)!");

        opcao3Questao3.setText("n * (n-1)!!!");

        lblQuestao3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuestao3.setText("03. Qual das escritas abaixo é igual ao fatorial de n?");

        lblQuestao4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuestao4.setText("04. Descubra a lógica e complete o próximo elemento:");

        lblResultado4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lblResultado5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lblQuestao5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuestao5.setText("05. Descubra a lógica e complete o próximo elemento:");

        opcao2Questao6.setText("1000 cm2");

        opcao3Questao6.setText("1350 cm2");

        lblQuestao6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuestao6.setText("06. Qual é a área total de um cubo cujas arestas medem 15 centímetros?");

        lblResultado6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        opcao1Questao6.setText("900 cm2");

        lblResultado7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lblQuestao7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuestao7.setText("07. Descubra a lógica e complete o próximo elemento:");

        lblResultado8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lblQuestao8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuestao8.setText("08. Descubra a lógica e complete o próximo elemento:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Corrigir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbQuestao2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbQuestao2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "n!!", "n*!", "n!", "n!!!" }));
        cbQuestao2.setSelectedIndex(-1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("1, 3, 5, 7,");

        tfQuestao4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("2, 4, 8, 16, 32, 64");

        tfQuestao5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("1, 1, 2, 3, 5, 8,");

        tfQuestao7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("2,10, 12, 16, 17, 18, 19,");

        tfQuestao8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(opcao1Questao6)
                                .addGap(18, 18, 18)
                                .addComponent(opcao2Questao6)
                                .addGap(10, 10, 10)
                                .addComponent(opcao3Questao6))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblQuestao1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblQuestao2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblQuestao3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblQuestao4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblQuestao5))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblQuestao6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tfQuestao7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblQuestao7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tfQuestao8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblQuestao8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultado6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResultado7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResultado8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(opcao1Questao1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(opcao2Questao1)
                                    .addGap(18, 18, 18)
                                    .addComponent(opcao3Questao1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(cbQuestao2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(opcao1Questao3)
                                    .addGap(34, 34, 34)
                                    .addComponent(opcao2Questao3)
                                    .addGap(29, 29, 29)
                                    .addComponent(opcao3Questao3))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfQuestao4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfQuestao5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblResultado5, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(lblResultado4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResultado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResultado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResultado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblQuestao1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcao1Questao1)
                    .addComponent(opcao2Questao1)
                    .addComponent(opcao3Questao1)
                    .addComponent(lblResultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblQuestao2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbQuestao2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblQuestao3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcao1Questao3)
                    .addComponent(opcao2Questao3)
                    .addComponent(opcao3Questao3)
                    .addComponent(lblResultado3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblQuestao4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfQuestao4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblQuestao5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfQuestao5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblQuestao6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcao1Questao6)
                    .addComponent(opcao2Questao6)
                    .addComponent(opcao3Questao6)
                    .addComponent(lblResultado6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblQuestao7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfQuestao7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultado7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblQuestao8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfQuestao8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (opcao1Questao1.isSelected()) {
            lblResultado1.setText("Correto");
            lblResultado1.setForeground(Color.GREEN);
        }else{
            lblResultado1.setText("Errado");
            lblResultado1.setForeground(Color.RED);
        }
        
        if (cbQuestao2.getSelectedIndex() == 2) {
            lblResultado2.setText("Correto");
            lblResultado2.setForeground(Color.GREEN);
        }else{
            lblResultado2.setText("Errado");
            lblResultado2.setForeground(Color.RED);
        }
        
        if (opcao2Questao3.isSelected()) {
            lblResultado3.setText("Correto");
            lblResultado3.setForeground(Color.GREEN);
        }else{
            lblResultado3.setText("Errado");
            lblResultado3.setForeground(Color.RED);
        }
        
        if (tfQuestao4.getText().equals("9")) {
            lblResultado4.setText("Correto");
            lblResultado4.setForeground(Color.GREEN);
        }else{
            lblResultado4.setText("Errado");
            lblResultado4.setForeground(Color.RED);
        }
         
        if (tfQuestao5.getText().equals("128")) {
            lblResultado5.setText("Correto");
            lblResultado5.setForeground(Color.GREEN);
        }else{
            lblResultado5.setText("Errado");
            lblResultado5.setForeground(Color.RED);
        }
        
        if (opcao3Questao6.isSelected()) {
            lblResultado6.setText("Correto");
            lblResultado6.setForeground(Color.GREEN);
        }else{
            lblResultado6.setText("Errado");
            lblResultado6.setForeground(Color.RED);
        }
        
        if (tfQuestao7.getText().equals("13")) {
            lblResultado7.setText("Correto");
            lblResultado7.setForeground(Color.GREEN);
        }else{
            lblResultado7.setText("Errado");
            lblResultado7.setForeground(Color.RED);
        }
        
        if (tfQuestao8.getText().equals("200")) {
            lblResultado8.setText("Correto");
            lblResultado8.setForeground(Color.GREEN);
        }else{
            lblResultado8.setText("Errado");
            lblResultado8.setForeground(Color.RED);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbQuestao2;
    private javax.swing.ButtonGroup grupoQuestao1;
    private javax.swing.ButtonGroup grupoQuestao3;
    private javax.swing.ButtonGroup grupoQuestao6;
    private javax.swing.ButtonGroup grupoQuestao8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblQuestao1;
    private javax.swing.JLabel lblQuestao2;
    private javax.swing.JLabel lblQuestao3;
    private javax.swing.JLabel lblQuestao4;
    private javax.swing.JLabel lblQuestao5;
    private javax.swing.JLabel lblQuestao6;
    private javax.swing.JLabel lblQuestao7;
    private javax.swing.JLabel lblQuestao8;
    private javax.swing.JLabel lblResultado1;
    private javax.swing.JLabel lblResultado2;
    private javax.swing.JLabel lblResultado3;
    private javax.swing.JLabel lblResultado4;
    private javax.swing.JLabel lblResultado5;
    private javax.swing.JLabel lblResultado6;
    private javax.swing.JLabel lblResultado7;
    private javax.swing.JLabel lblResultado8;
    private javax.swing.JRadioButton opcao1Questao1;
    private javax.swing.JRadioButton opcao1Questao3;
    private javax.swing.JRadioButton opcao1Questao6;
    private javax.swing.JRadioButton opcao2Questao1;
    private javax.swing.JRadioButton opcao2Questao3;
    private javax.swing.JRadioButton opcao2Questao6;
    private javax.swing.JRadioButton opcao3Questao1;
    private javax.swing.JRadioButton opcao3Questao3;
    private javax.swing.JRadioButton opcao3Questao6;
    private javax.swing.JTextField tfQuestao4;
    private javax.swing.JTextField tfQuestao5;
    private javax.swing.JTextField tfQuestao7;
    private javax.swing.JTextField tfQuestao8;
    // End of variables declaration//GEN-END:variables
}
